resolver: lts-17.4

packages:
  - .

extra-deps:
  - github: GrammaticalFramework/gf-core
    commit: 7dc6717b5e95122a810d3b580981fc4ce0c9744b
  - json-0.10@sha256:d9fc6b07ce92b8894825a17d2cf14799856767eb30c8bf55962baa579207d799,3210
  - lsp-1.1.1.0
  - lsp-types-1.1.0.0
  - dependent-map-0.4.0.0
  - dependent-sum-0.7.1.0
  - dependent-sum-template-0.1.0.3
  - constraints-extras-0.3.0.2
  - unliftio-core-0.2.0.1
  - some-1.0.1

flags:
  # this excludes PGF2 module in gf package
  gf:
    c-runtime: false
    server: false
