name:                diagrams-sandbox
version:             0.1.0.0
github:              "githubuser/diagrams-sandbox"
license:             BSD3
author:              "Jo Hsi"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/diagrams-sandbox#readme>

dependencies:
- base >= 4.7 && < 5
- diagrams
- diagrams-lib
- diagrams-svg
- diagrams-contrib

library:
  source-dirs: src

# executables:
#  diagrams-sandbox-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - diagrams-sandbox

tests:
  diagrams-sandbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diagrams-sandbox
