name:                language-python-experiment
version:             0.1.0.0
github:              "githubuser/language-python-experiment"
license:             BSD3
author:              "2jacobtan"
maintainer:          "example@example.com"
copyright:           "2021 2jacobtan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/language-python-experiment#readme>

dependencies:
- base >= 4.7 && < 5
- language-python

library:
  source-dirs: src

executables:
  language-python-experiment-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-python-experiment

tests:
  language-python-experiment-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - language-python-experiment
